import requests
from datetime import date

areas = {
    "SK0101": "Okres Bratislava I",
    "SK0102": "Okres Bratislava II",
    "SK0103": "Okres Bratislava III",
    "SK0104": "Okres Bratislava IV",
    "SK0105": "Okres Bratislava V",
    "SK0106": "Okres Malacky",
    "SK0107": "Okres Pezinok",
    "SK0108": "Okres Senec",
    "SK0211": "Okres Dunajská Streda",
    "SK0212": "Okres Galanta",
    "SK0213": "Okres Hlohovec",
    "SK0214": "Okres Piešťany",
    "SK0215": "Okres Senica",
    "SK0216": "Okres Skalica",
    "SK0217": "Okres Trnava",
    "SK0221": "Okres Bánovce nad Bebravou",
    "SK0222": "Okres Ilava",
    "SK0223": "Okres Myjava",
    "SK0224": "Okres Nové Mesto nad Váhom",
    "SK0225": "Okres Partizánske",
    "SK0226": "Okres Považská Bystrica",
    "SK0227": "Okres Prievidza",
    "SK0228": "Okres Púchov",
    "SK0229": "Okres Trenčín",
    "SK0231": "Okres Komárno",
    "SK0232": "Okres Levice",
    "SK0233": "Okres Nitra",
    "SK0234": "Okres Nové Zámky",
    "SK0235": "Okres Šaľa",
    "SK0236": "Okres Topoľčany",
    "SK0237": "Okres Zlaté Moravce",
    "SK0311": "Okres Bytča",
    "SK0312": "Okres Čadca",
    "SK0313": "Okres Dolný Kubín",
    "SK0314": "Okres Kysucké Nové Mesto",
    "SK0315": "Okres Liptovský Mikuláš",
    "SK0316": "Okres Martin",
    "SK0317": "Okres Námestovo",
    "SK0318": "Okres Ružomberok",
    "SK0319": "Okres Turčianske Teplice",
    "SK031A": "Okres Tvrdošín",
    "SK031B": "Okres Žilina",
    "SK0321": "Okres Banská Bystrica",
    "SK0322": "Okres Banská Štiavnica",
    "SK0323": "Okres Brezno",
    "SK0324": "Okres Detva",
    "SK0325": "Okres Krupina",
    "SK0326": "Okres Lučenec",
    "SK0327": "Okres Poltár",
    "SK0328": "Okres Revúca",
    "SK0329": "Okres Rimavská Sobota",
    "SK032A": "Okres Veľký Krtíš",
    "SK032B": "Okres Zvolen",
    "SK032C": "Okres Žarnovica",
    "SK032D": "Okres Žiar nad Hronom",
    "SK0411": "Okres Bardejov",
    "SK0412": "Okres Humenné",
    "SK0413": "Okres Kežmarok",
    "SK0414": "Okres Levoča",
    "SK0415": "Okres Medzilaborce",
    "SK0416": "Okres Poprad",
    "SK0417": "Okres Prešov",
    "SK0418": "Okres Sabinov",
    "SK0419": "Okres Snina",
    "SK041A": "Okres Stará Ľubovňa",
    "SK041B": "Okres Stropkov",
    "SK041C": "Okres Svidník",
    "SK041D": "Okres Vranov nad Topľou",
    "SK0421": "Okres Gelnica",
    "SK0422": "Okres Košice I",
    "SK0423": "Okres Košice II",
    "SK0424": "Okres Košice III",
    "SK0425": "Okres Košice IV",
    "SK0426": "Okres Košice - okolie",
    "SK0427": "Okres Michalovce",
    "SK0428": "Okres Rožňava",
    "SK0429": "Okres Sobrance",
    "SK042A": "Okres Spišská Nová Ves",
    "SK042B": "Okres Trebišov",
}


class dataset:
    def __init__(self, kod, nazov, od, dimenzie):
        self.kod_datasetu = kod
        self.nazov = nazov
        self.udaje_od_roku = od
        self.dimenzie = dimenzie
        
    def __repr__(self):
        return self.kod_datasetu

def generuj_roky(od):
    vysledok = []
    for i in range(od, date.today().year):
        vysledok.append(i)
    return vysledok

datasety = []

#1. - dataset 
# TODO: oprav generuj roky
datasety.append(
    dataset("om7102rr",
             "Počet obyvateľov podľa pohlavia - SR-oblasť-kraj-okres, m-v (ročne)",
             1993,
             [{"nazov": "Okresy",
               "kod" : "om7102rr_vuc",
               "udaje": areas},
              {"nazov": "Roky",
               "kod" : "om7102rr_obd",
               "udaje": generuj_roky(2020)},
              {"nazov": "Ukazovatele",
               "kod" : "om7102rr_ukaz",
               "udaje": {
                    0 : "Stav trvale bývajúceho obyvateľstva na začiatku obdobia (Osoba)",
                    1 : "Stredný (priemerný) stav trvale bývajúceho obyvateľstva (Osoba)",
                    2 : "Stav trvale bývajúceho obyvateľstva na konci obdobia (Osoba)"}},
              {"nazov": "Pohlavie",
               "kod" : "om7102rr_poh",
               "udaje": {
                    0 : "Spolu",
                    1 : "Muži",
                    2 : "Ženy",}},
              ]))

#2. - dataset
datasety.append(
    dataset("om7038rr",
            "Priemerný vek osoby pri úmrtí podľa pohlavia - SR-oblasť-kraj-okres, m-v",
            1993,
            [{"nazov": "Okresy",
               "kod" : "om7038rr_vuc",
               "udaje": areas},
             {"nazov": "Roky",
               "kod" : "om7038rr_obd",
               "udaje": generuj_roky(1993)},
             {"nazov": "Ukazovatele",
              "kod" : "om7038rr_ukaz",
              "udaje": {
                    0 : "Priemerný vek pri úmrtí (Rok)"}},
             {"nazov": "Pohlavie",
               "kod" : "om7038rr_poh",
               "udaje": {
                    0 : "Spolu",
                    1 : "Muži",
                    2 : "Ženy",}},
             ]))

#3. - dataset
datasety.append(
    dataset("om7034rr",
            "Zomrelí podľa veku a pohlavia - SR-oblasť-kraj-okres, m-v",
            1993,
            [{"nazov": "Okresy",
               "kod" : "om7034rr_vuc",
               "udaje": areas},
            {"nazov": "Roky",
               "kod" : "om7034rr_obd",
               "udaje": generuj_roky(1993)},
             {"nazov" : "Vek",
              "kod" : "om7034rr_vek",
              "udaje" : {
                    0 : "Spolu",
                    1 : "Menej ako 7 dní",
                    2 : "Menej ako 28 dní",
                    3 : "Menej ako 1 rok",
                    4 : "1 rok",
                    5 : "2 roky",
                    6 : "3 roky",
                    7 : "4 roky",
                    8 : "5 rokov",
                    9 : "6 rokov",
                    10 : "7 rokov",
                    11 : "8 rokov",
                    12 : "9 rokov",
                    13 : "10 rokov",
                    14 : "11 rokov",
                    15 : "12 rokov",
                    16 : "13 rokov",
                    17 : "14 rokov",
                    18 : "15 rokov",
                    19 : "16 rokov",
                    20 : "17 rokov",
                    21 : "18 rokov",
                    22 : "19 rokov",
                    23 : "20 rokov",
                    24 : "21 rokov",
                    25 : "22 rokov",
                    26 : "23 rokov",
                    27 : "24 rokov",
                    28 : "25 rokov",
                    29 : "26 rokov",
                    30 : "27 rokov",
                    31 : "28 rokov",
                    32 : "29 rokov",
                    33 : "30 rokov",
                    34 : "31 rokov",
                    35 : "32 rokov",
                    36 : "33 rokov",
                    37 : "34 rokov",
                    38 : "35 rokov",
                    39 : "36 rokov",
                    40 : "37 rokov",
                    41 : "38 rokov",
                    42 : "39 rokov",
                    43 : "40 rokov",
                    44 : "41 rokov",
                    45 : "42 rokov",
                    46 : "43 rokov",
                    47 : "44 rokov",
                    48 : "45 rokov",
                    49 : "46 rokov",
                    50 : "47 rokov",
                    51 : "48 rokov",
                    52 : "49 rokov",
                    53 : "50 rokov",
                    54 : "51 rokov",
                    55 : "52 rokov",
                    56 : "53 rokov",
                    57 : "54 rokov",
                    58 : "55 rokov",
                    59 : "56 rokov",
                    60 : "57 rokov",
                    61 : "58 rokov",
                    62 : "59 rokov",
                    63 : "60 rokov",
                    64 : "61 rokov",
                    65 : "62 rokov",
                    66 : "63 rokov",
                    67 : "64 rokov",
                    68 : "65 rokov",
                    69 : "66 rokov",
                    70 : "67 rokov",
                    71 : "68 rokov",
                    72 : "69 rokov",
                    73 : "70 rokov",
                    74 : "71 rokov",
                    75 : "72 rokov",
                    76 : "73 rokov",
                    77 : "74 rokov",
                    78 : "75 rokov",
                    79 : "76 rokov",
                    80 : "77 rokov",
                    81 : "78 rokov",
                    82 : "79 rokov",
                    83 : "80 rokov",
                    84 : "81 rokov",
                    85 : "82 rokov",
                    86 : "83 rokov",
                    87 : "84 rokov",
                    88 : "85 rokov",
                    89 : "86 rokov",
                    90 : "87 rokov",
                    91 : "88 rokov",
                    92 : "89 rokov",
                    93 : "90 rokov",
                    94 : "91 rokov",
                    95 : "92 rokov",
                    96 : "93 rokov",
                    97 : "94 rokov",
                    98 : "95 rokov",
                    99 : "96 rokov",
                    100 : "97 rokov",
                    101 : "98 rokov",
                    102 : "99 rokov",
                    103 : "Od 1 do 4 rokov",
                    104 : "Od 5 do 9 rokov",
                    105 : "Od 10 do 14 rokov",
                    106 : "Od 15 do 19 rokov",
                    107 : "Od 20 do 24 rokov",
                    108 : "Od 25 do 29 rokov",
                    109 : "Od 30 do 34 rokov",
                    110 : "Od 35 do 39 rokov",
                    111 : "Od 40 do 44 rokov",
                    112 : "Od 45 do 49 rokov",
                    113 : "Od 50 do 54 rokov",
                    114 : "Od 55 do 59 rokov",
                    115 : "Od 60 do 64 rokov",
                    116 : "Od 65 do 69 rokov",
                    117 : "Od 70 do 74 rokov",
                    118 : "Od 75 do 79 rokov",
                    119 : "Od 80 do 84 rokov",
                    120 : "Od 85 do 89 rokov",
                    121 : "85 rokov alebo viac",
                    122 : "Od 90 do 94 rokov",
                    123 : "Od 95 do 99 rokov",
                    124 : "100 rokov alebo viac"}},
             {"nazov": "Pohlavie",
               "kod" : "om7034rr_poh",
               "udaje": {
                    0 : "Spolu",
                    1 : "Muži",
                    2 : "Ženy",}},
            ]))

#4. - dataset
datasety.append(
    dataset("om7009rr",
            "Vekové zloženie - SR-oblasť-kraj-okres, m-v",
            1996,
            [{"nazov": "Okresy",
               "kod" : "om7009rr_vuc",
               "udaje": areas},
             {"nazov": "Roky",
               "kod" : "om7009rr_obd",
               "udaje": generuj_roky(1996)},
             {"nazov": "Ukazovatele",
              "kod" : "om7009rr_ukaz",
              "udaje": {
                    0 : "Stav trvale bývajúceho obyvateľstva k 30.6.(1.7.) (Osoba)",
                    1 : "Stav trvale bývajúceho obyvateľstva k 31.12. (Osoba)"}},
             {"nazov": "Pohlavie",
               "kod" : "om7009rr_poh",
               "udaje": {
                    0 : "Spolu",
                    1 : "Muži",
                    2 : "Ženy",}}, 
             {"nazov": "Jednotky veku",
               "kod" : "om7009rr_vek",
               "udaje": {
                    0 : "Spolu",
                    1 : "Nula rokov",
                    2 : "1 rok",
                    3 : "2 roky",
                    4 : "3 roky",
                    5 : "4 roky",
                    6 : "5 rokov",
                    7 : "6 rokov",
                    8 : "7 rokov",
                    9 : "8 rokov",
                    10 : "9 rokov",
                    11 : "10 rokov",
                    12 : "11 rokov",
                    13 : "12 rokov",
                    14 : "13 rokov",
                    15 : "14 rokov",
                    16 : "15 rokov",
                    17 : "16 rokov",
                    18 : "17 rokov",
                    19 : "18 rokov",
                    20 : "19 rokov",
                    21 : "20 rokov",
                    22 : "21 rokov",
                    23 : "22 rokov",
                    24 : "23 rokov",
                    25 : "24 rokov",
                    26 : "25 rokov",
                    27 : "26 rokov",
                    28 : "27 rokov",
                    29 : "28 rokov",
                    30 : "29 rokov",
                    31 : "30 rokov",
                    32 : "31 rokov",
                    33 : "32 rokov",
                    34 : "33 rokov",
                    35 : "34 rokov",
                    36 : "35 rokov",
                    37 : "36 rokov",
                    38 : "37 rokov",
                    39 : "38 rokov",
                    40 : "39 rokov",
                    41 : "40 rokov",
                    42 : "41 rokov",
                    43 : "42 rokov",
                    44 : "43 rokov",
                    45 : "44 rokov",
                    46 : "45 rokov",
                    47 : "46 rokov",
                    48 : "47 rokov",
                    49 : "48 rokov",
                    50 : "49 rokov",
                    51 : "50 rokov",
                    52 : "51 rokov",
                    53 : "52 rokov",
                    54 : "53 rokov",
                    55 : "54 rokov",
                    56 : "55 rokov",
                    57 : "56 rokov",
                    58 : "57 rokov",
                    59 : "58 rokov",
                    60 : "59 rokov",
                    61 : "60 rokov",
                    62 : "61 rokov",
                    63 : "62 rokov",
                    64 : "63 rokov",
                    65 : "64 rokov",
                    66 : "65 rokov",
                    67 : "66 rokov",
                    68 : "67 rokov",
                    69 : "68 rokov",
                    70 : "69 rokov",
                    71 : "70 rokov",
                    72 : "71 rokov",
                    73 : "72 rokov",
                    74 : "73 rokov",
                    75 : "74 rokov",
                    76 : "75 rokov",
                    77 : "76 rokov",
                    78 : "77 rokov",
                    79 : "78 rokov",
                    80 : "79 rokov",
                    81 : "80 rokov",
                    82 : "81 rokov",
                    83 : "82 rokov",
                    84 : "83 rokov",
                    85 : "84 rokov",
                    86 : "85 rokov",
                    87 : "86 rokov",
                    88 : "87 rokov",
                    89 : "88 rokov",
                    90 : "89 rokov",
                    91 : "90 rokov",
                    92 : "91 rokov",
                    93 : "92 rokov",
                    94 : "93 rokov",
                    95 : "94 rokov",
                    96 : "95 rokov",
                    97 : "96 rokov",
                    98 : "97 rokov",
                    99 : "98 rokov",
                    100 : "99 rokov",
                    101 : "100 rokov",
                    102 : "100 rokov alebo viac",
                    103 : "101 rokov",
                    104 : "102 rokov",
                    105 : "103 rokov",
                    106 : "104 rokov",
                    107 : "105 rokov",
                    108 : "106 rokov",
                    109 : "107 rokov",
                    110 : "108 rokov",
                    111 : "109 rokov",
                    112 : "110 rokov alebo viac"}}
            ]))

#5. - dataset
datasety.append(
    dataset("om7011rr",
            "Prehľad stavu a pohybu obyvateľstva - SR-oblasť-kraj-okres, m-v",
            1996,
            [{"nazov": "Okresy",
               "kod" : "om7011rr_vuc",
               "udaje": areas},
             {"nazov": "Roky",
               "kod" : "om7011rr_obd",
               "udaje": generuj_roky(1996)},
             {"nazov": "Ukazovatele",
               "kod" : "om7011rr_ukaz",
               "udaje": {
                    0 : "Stav trvale bývajúceho obyvateľstva k 1.1. (Osoba)",
                    1 : "Stav trvale bývajúceho obyvateľstva k 30.6.(1.7.) (Osoba)",
                    2 : "Stav trvale bývajúceho obyvateľstva k 31.12. (Osoba)",
                    3 : "Narodení (Osoba)",
                    4 : "Hrubá miera živorodenosti (Promile)",
                    5 : "Potraty (Počet v jednotkách)",
                    6 : "Hrubá miera potratovosti (Promile)",
                    7 : "Index potratovosti (Percento)",
                    8 : "Ukončené tehotenstvá (Počet v jednotkách)",
                    9 : "Hrubá miera ukončených tehotenstiev (Promile)",
                    10 : "Zomretí (Osoba)",
                    11 : "Hrubá miera úmrtnosti (Promile)",
                    12 : "Dojčenská úmrtnosť (Osoba)",
                    13 : "Miera dojčenskej úmrtnosti (Promile)",
                    14 : "Novorodenecká úmrtnosť (Osoba)",
                    15 : "Miera novorodeneckej úmrtnosti (Promile)",
                    16 : "Perinatálna úmrtnosť (Osoba)",
                    17 : "Miera perinatálnej úmrtnosti (Promile)",
                    18 : "Štandardná dojčenská úmrtnosť (Promile)",
                    19 : "Štandardná novorodenecká úmrtnosť (Promile)",
                    20 : "Sobáše (Počet v jednotkách)",
                    21 : "Hrubá miera sobášnosti (Promile)",
                    22 : "Rozvody (Počet v jednotkách)",
                    23 : "Hrubá miera rozvodovosti (Promile)",
                    24 : "Index rozvodovosti (Percento)",
                    25 : "Prirodzený prírastok obyvateľstva (Osoba)",
                    26 : "Hrubá miera prirodzeného prírastku obyvateľstva (Promile)",
                    27 : "Prisťahovaní na trvalý pobyt (Osoba)",
                    28 : "Vysťahovaní z trvalého pobytu (Osoba)",
                    29 : "Migračné saldo (Osoba)",
                    30 : "Hrubá miera migračného salda (Promile)",
                    31 : "Celkový prírastok obyvateľstva (Osoba)",
                    32 : "Hrubá miera celkového prírastku obyvateľstva (Promile)",
                    33 : "Živonarodení (Osoba)"}}
            ]))

#6. - dataset
datasety.append(
    dataset("om7023rr",
            "Veľkostné skupiny obcí - SR-oblasť-kraj-okres, m-v",
            1996,
            [{"nazov": "Okresy",
               "kod" : "om7023rr_vuc",
               "udaje": areas},
             {"nazov": "Roky",
               "kod" : "om7023rr_obd",
               "udaje": generuj_roky(1996)},
             {"nazov": "Ukazovatele",
               "kod" : "om7023rr_ukaz",
               "udaje": {
                    0 : "Stav trvale bývajúceho obyvateľstva k 31.12. (Osoba)",
                    1 : "Počet obcí (Počet v jednotkách)"}},
             {"nazov": "Velkostné skupiny obcí",
               "kod" : "om7023rr_vsk",
               "udaje": {
                    0 : "1 999 obyvatelov alebo menej",
                    1 : "Skupina 199 obyvateľov alebo menej",
                    2 : "99 obyvateľov alebo menej",
                    3 : "Od 100 do 199 obyvateľov",
                    4 : "Skupina Od 200 do 499 obyvateľov",
                    5 : "Od 200 do 299 obyvateľov",
                    6 : "Od 300 do 399 obyvateľov",
                    7 : "Od 400 do 499 obyvateľov",
                    8 : "Skupina Od 500 do 999 obyvateľov",
                    9 : "Od 500 do 599 obyvateľov",
                    10 : "Od 600 do 699 obyvateľov",
                    11 : "Od 700 do 799 obyvateľov",
                    12 : "Od 800 do 899 obyvateľov",
                    13 : "Od 900 do 999 obyvateľov",
                    14 : "Skupina Od 1 000 do 1 999 obyvateľov",
                    15 : "Od 1 000 do 1 499 obyvateľov",
                    16 : "Od 1 500 do 1 999 obyvateľov",
                    17 : "2 000 a viac obyvatelov",
                    18 : "Skupina Od 2 000 do 4 999 obyvateľov",
                    19 : "Od 2 000 do 2 499 obyvateľov",
                    20 : "Od 2 500 do 2 999 obyvateľov",
                    21 : "Od 3 000 do 3 999 obyvateľov",
                    22 : "Od 4 000 do 4 999 obyvateľov",
                    23 : "Skupina Od 5 000 do 9 999 obyvateľov",
                    24 : "Od 5 000 do 9 999 obyvateľov",
                    25 : "Skupina Od 10 000 do 19 999 obyvateľov",
                    26 : "Od 10 000 do 14 999 obyvateľov",
                    27 : "Od 15 000 do 19 999 obyvateľov",
                    28 : "Skupina Od 20 000 do 49 999 obyvateľov",
                    29 : "Od 20 000 do 24 999 obyvateľov",
                    30 : "Od 25 000 do 29 999 obyvateľov",
                    31 : "Od 30 000 do 39 999 obyvateľov",
                    32 : "Od 40 000 do 49 999 obyvateľov",
                    33 : "Skupina Od 50 000 do 99 999 obyvateľov",
                    34 : "Od 50 000 do 99 999 obyvateľov",
                    35 : "Skupina 100 000 a viac obyvateľov",
                    36 : "100 000 a viac obyvateľov"}}
            ]))

#7. - dataset
datasety.append(
    dataset("om7023rr",
            "Veľkostné skupiny obcí - SR-oblasť-kraj-okres, m-v",
            1996,
            [{"nazov": "Okresy",
               "kod" : "om7023rr_vuc",
               "udaje": areas},
             {"nazov": "Roky",
               "kod" : "om7023rr_obd",
               "udaje": generuj_roky(1996)},
             {"nazov": "Ukazovatele",
               "kod" : "om7023rr_vuc",
               "udaje": {
                    0 : "Stav trvale bývajúceho obyvateľstva k 31.12. (Osoba)",
                    1 : "Počet obcí (Počet v jednotkách)"}},
             {"nazov": "Velkostné skupiny obcí",
               "kod" : "om7023rr_vsk",
               "udaje": {
                    0 : "1 999 obyvatelov alebo menej",
                    1 : "Skupina 199 obyvateľov alebo menej",
                    2 : "99 obyvateľov alebo menej",
                    3 : "Od 100 do 199 obyvateľov",
                    4 : "Skupina Od 200 do 499 obyvateľov",
                    5 : "Od 200 do 299 obyvateľov",
                    6 : "Od 300 do 399 obyvateľov",
                    7 : "Od 400 do 499 obyvateľov",
                    8 : "Skupina Od 500 do 999 obyvateľov",
                    9 : "Od 500 do 599 obyvateľov",
                    10 : "Od 600 do 699 obyvateľov",
                    11 : "Od 700 do 799 obyvateľov",
                    12 : "Od 800 do 899 obyvateľov",
                    13 : "Od 900 do 999 obyvateľov",
                    14 : "Skupina Od 1 000 do 1 999 obyvateľov",
                    15 : "Od 1 000 do 1 499 obyvateľov",
                    16 : "Od 1 500 do 1 999 obyvateľov",
                    17 : "2 000 a viac obyvatelov",
                    18 : "Skupina Od 2 000 do 4 999 obyvateľov",
                    19 : "Od 2 000 do 2 499 obyvateľov",
                    20 : "Od 2 500 do 2 999 obyvateľov",
                    21 : "Od 3 000 do 3 999 obyvateľov",
                    22 : "Od 4 000 do 4 999 obyvateľov",
                    23 : "Skupina Od 5 000 do 9 999 obyvateľov",
                    24 : "Od 5 000 do 9 999 obyvateľov",
                    25 : "Skupina Od 10 000 do 19 999 obyvateľov",
                    26 : "Od 10 000 do 14 999 obyvateľov",
                    27 : "Od 15 000 do 19 999 obyvateľov",
                    28 : "Skupina Od 20 000 do 49 999 obyvateľov",
                    29 : "Od 20 000 do 24 999 obyvateľov",
                    30 : "Od 25 000 do 29 999 obyvateľov",
                    31 : "Od 30 000 do 39 999 obyvateľov",
                    32 : "Od 40 000 do 49 999 obyvateľov",
                    33 : "Skupina Od 50 000 do 99 999 obyvateľov",
                    34 : "Od 50 000 do 99 999 obyvateľov",
                    35 : "Skupina 100 000 a viac obyvateľov",
                    36 : "100 000 a viac obyvateľov"}}
            ]))

#8. - dataset
datasety.append(
    dataset("om7015rr",
            "Hustota obyvateľstva - SR-oblasť-kraj-okres, m-v",
            1996,
            [{"nazov": "Okresy",
               "kod" : "om7015rr_vuc",
               "udaje": areas},
             {"nazov": "Roky",
               "kod" : "om7015rr_obd",
               "udaje": generuj_roky(1996)},
             {"nazov": "Ukazovatele",
               "kod" : "om7015rr_ukaz",
               "udaje": {
                    0 : "Hustota obyvateľstva (Osoba na kilometer štvorcový)",
                    1 : "Rozloha (Štvorcový meter)",
                    2 : "Stav trvale bývajúceho obyvateľstva k 30.6.(1.7.) (Osoba)"}}
            ]))

# print(datasety[0].dimenzie[1:])

def permutacie_parametrov(dataset):

  permutacie = []
  for rok in dataset.dimenzie[1]["udaje"]:
    permutacie.append([rok])


  for dimenzia in dataset.dimenzie[2:]:
    nove = []
    for parameter in dimenzia["udaje"]:
      for riadok in permutacie:
        nove.append(riadok+[parameter])
    permutacie = nove
    
  return permutacie

print(permutacie_parametrov(datasety[0]))

'''
def stahuj(dataset, permuracie):
  for parameter in permutacie:
    data = {}
    for okres in okresy:
      data[orkes] = stiahni(parameter, okres)
    vlozdodatabazy(data)
'''
